global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'webapp'
    metrics_path: /metrics
    static_configs:
      - targets: ['webapp:5233']